hiring_manager_bc/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get "/auth/:provider/callback" => 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  patch 'applications/:id/approve' => 'applications#approve_applicant', as: :application_approve
  patch 'applications/:id/reject' => 'applications#reject_applicant', as: :application_reject
  resources :sessions, only: :index
  resources :applications
  resources :interviews
  resources :feedbacks
end

hiring_manager_bc/app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :candidate, optional: true
  has_many :interviews
  validates :candidate_id, presence: true
  validates :user_id, presence: true
  validates :experience, presence: true, length: { maximum: 50 }
  validates :qualification, presence: true, length: { maximum: 50 }
  validates :contact_number, presence: true, length: { maximum: 10 }
  validates :exp_salary, presence: true
  validates :notice_period, presence: true, length: { maximum: 50 }
  validates :assigned_to, presence: true, length: { maximum: 50 }
  validates :status, presence: true, length: { maximum: 50 }
end

hiring_manager_bc/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  mount_uploader :resume, ResumeUploader
end

hiring_manager_bc/app/models/candidate.rb
class Candidate < ApplicationRecord
    has_many :applications
end

hiring_manager_bc/app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :interview
end

hiring_manager_bc/app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :application
  belongs_to :user
  has_many :feedbacks
end

hiring_manager_bc/app/models/user.rb
class User < ApplicationRecord
    has_many :applications
    has_many :interviews
end

hiring_manager_bc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper


  private

  # Confirms a logged-in user.
  def logged_in_user
   unless logged_in?
     flash.now[:danger] = "Please log in."
     redirect_to root_path
   end
 end
end

hiring_manager_bc/app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :logged_in_user

  def new
    @application = current_user.applications.new
    @candidate = Candidate.new
  end

  def index
    if params[:search]
      @applications = Application.where('assigned_to LIKE ?', "%#{params[:search]}%")
    else
      @applications = Application.all
    end
    @candidates = Candidate.all
    @users = User.all
  end

  def show
    @application = Application.find(params[:id])
    @candidate = Candidate.find_by(id: @application.candidate_id)
    @interview = Interview.new
    @feedback = Feedback.new
    @interviews = Interview.all
    @app_interviews = @interviews.where(application_id: params[:id])
  end

  def create 
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      @application = current_user.applications.new(application_params)
      @application.candidate_id = @candidate.id
        if @application.save
          redirect_to @application
        else
          render 'new'
        end
    end
  end

  def edit
    @application = Application.find(params[:id])
    @candidate = Candidate.find_by(id: @application.candidate_id)
  end

  def update
    @application = Application.find(params[:id])
    byebug
    if @application.update_attributes(application_params)
      flash[:success] = "Profile updated"
      redirect_to @application
    else
      render 'edit'
    end
  end

  def destroy
    @application = Application.find(params[:id])
    @application.destroy
    flash[:success] = "Application deleted"
    redirect_to applications_path
  end

  def approve_applicant
    @application = Application.find(params[:id])
    @application.update_attributes(status: "Approved")
    redirect_to @application
  end

  def reject_applicant
    @application = Application.find(params[:id])
    @application.update_attributes(status: "Rejected")
    redirect_to @application
  end
  
  private

    def application_params
      params.require(:application).permit(:experience, :qualification, :contact_number,
                                   :exp_salary, :notice_period, :assigned_to, :status, :user_id, :candidate_id, :resume)
    end
    def candidate_params
      params[:application][:candidates].permit(:name, :email, :dob, :gender)
    end
end

hiring_manager_bc/app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @interviews = Interview.all
    @feedbacks = Feedback.all
  end

  def create
    @application = Application.find_by(params[:id])
    @user = User.find_by(id: @application.user_id)
    @interviews = Interview.find_by(application_id: @application.id)
    @feedback = @interviews.feedbacks.new(feedback_params)
    if @feedback.save
      UserMailer.new_feedback(@user).deliver_now
      flash[:info] = "Please check your email to."
      redirect_to @application
    else
      redirect_to @application
    end
  end


  private

  def feedback_params
    params.require(:feedback).permit(:message)
  end
end

hiring_manager_bc/app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
    before_action :logged_in_user

    def new
        @interview = Interview.new
    end

    def create
        @application = Application.find(params[:interview][:application_id])
        byebug
        @user = User.find_by(id: @application.user_id)
        @interview = current_user.interviews.build(interview_params)
        @interview.application_id = @application.id
        if @interview.save
            UserMailer.new_interview(@user).deliver_now
            flash[:success] = "Interview created!"
            redirect_to @application
        else
            render 'applications/show'
        end
    end

    def destroy
    end

    private

    def interview_params
      params.require(:interview).permit(:interview_type, :assignee)
    end
end

hiring_manager_bc/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = request.env['omniauth.auth']['info']['email']
    name = request.env['omniauth.auth']['info']['name']
    add_or_update_user name, email
  end

  def destroy
    log_out
    redirect_to root_url
  end

  private

  def add_or_update_user(name, email)
    if name && email
      @auth = request.env['omniauth.auth']['credentials']
      @user_exist = User.find_by(email: email)
      if @user_exist
        @user = @user_exist.update_attributes(name: name)
        login_and_redirect email
      else
        @user = User.new(name: name, email: email, role: "Interviewer")
        if @user.save
          login_and_redirect email
        else
          flash.now[:danger] = 'Invalid user'
          render 'new'
        end
      end
    end
  end

  def login_and_redirect(email)
    log_in email
    redirect_to applications_path
  end
end

hiring_manager_bc/app/helpers/application_helper.rb
module ApplicationHelper
end

hiring_manager_bc/app/helpers/applications_helper.rb
module ApplicationsHelper
end

hiring_manager_bc/app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

hiring_manager_bc/app/helpers/interviews_helper.rb
module InterviewsHelper
end

hiring_manager_bc/app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(email)
      session[:user_id] = email
    end
  
    # Returns the current logged-in user (if any).
    def current_user
      if session[:user_id]
        @current_user ||= User.find_by(email: session[:user_id])
      end
    end
  
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
      !current_user.nil?
    end
  
    # Logs out the current user.
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  end
  

hiring_manager_bc/app/views/applications/edit.html.erb
<h1>Update the Application info</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 new-form">
    <%= form_for(@application) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :experience %>
      <%= f.text_field :experience, class: 'form-control'  %>

      <%= f.label :qualification %>
      <%= f.text_field :qualification, class: 'form-control'  %>

      <%= f.label :contact_number %>
      <%= f.text_field :contact_number, class: 'form-control'  %>

      <%= f.label :exp_salary %>
      <%= f.text_field :exp_salary, class: 'form-control'  %>

      <%= f.label :notice_period %>
      <%= f.text_field :notice_period, class: 'form-control'  %>

      <%= f.label :assigned_to %>
      <%= f.text_field :assigned_to, class: 'form-control'  %>

      <%= f.label :status %>
      <%= f.text_field :status, class: 'form-control'  %>

      <%= f.label :resume %>
      <%= f.file_field :resume, class: 'form-control'  %>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

hiring_manager_bc/app/views/applications/index.html.erb
<h1>Welcome! <%= current_user.name %></h1>
  <% if @applications.any? == true %>
  <div class="col-sm-7 search-bar">
  <%= form_tag applications_path, :method =>  'get' do %>
      <%= text_field_tag :search, params[:search]%>
      <%= submit_tag 'Search', :name => nil %>
  <% end %>
  </div>
    <table class="table table-bordered table-responsive">
      <thead>
        <tr>
          <th>S.No</th>
          <th>NAME</th>
          <th>STATUS</th>
          <th>ASSIGNED TO</th>
        </tr>
      </thead>
      <% @applications.each do |applicant| %>
        <% candidate = @candidates.find_by(id: applicant.candidate_id) %>
        <% assignee = @users.find_by(id: applicant.user_id) %> 
        <tr>
          <td><%= applicant.id%></td>
          <td><%= link_to candidate.name, application_path(applicant) %></td>
          <td><%= applicant.status %></td>
          <td><%= applicant.assigned_to %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <h1>Sorry! but you don't have any candidates at the moment!</h1>
  <% end %>
<% if current_user.role === "Manager" %>
    <%= link_to "Add an applicant", new_application_path , class: "btn btn-lg btn-primary action-button" %>
<% end %>

hiring_manager_bc/app/views/applications/new.html.erb
<h1>Add a new Candidate</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 new-form">
    <%= form_for(@application) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.fields_for :candidates do |candidate_field| %>
        <%= candidate_field.text_field :name, class: 'form-control'%>
      <% end %>

      <%= f.label :email %>
      <%= f.fields_for :candidates do |candidate_field| %>
        <%= candidate_field.email_field :email, class: 'form-control'%>
      <% end %>

      <%= f.label :date_of_birth %>
      <%= f.fields_for :candidates do |candidate_field| %>
        <%= candidate_field.text_field :dob, class: 'form-control'%>
      <% end %>

      <%= f.label :gender %>
      <%= f.fields_for :candidates do |candidate_field| %>
        <%= candidate_field.text_field :gender, class: 'form-control'%>
      <% end %>

      <%= f.label :experience %>
      <%= f.text_field :experience, class: 'form-control'  %>

      <%= f.label :qualification %>
      <%= f.text_field :qualification, class: 'form-control'  %>

      <%= f.label :contact_number %>
      <%= f.text_field :contact_number, class: 'form-control'  %>

      <%= f.label :exp_salary %>
      <%= f.text_field :exp_salary, class: 'form-control'  %>

      <%= f.label :notice_period %>
      <%= f.text_field :notice_period, class: 'form-control'  %>

      <%= f.label :assigned_to %>
      <%= f.text_field :assigned_to, class: 'form-control'  %>

      <%= f.label :status %>
      <%= f.text_field :status, class: 'form-control'  %>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

hiring_manager_bc/app/views/applications/show.html.erb
<div class="row">
    <aside class="col-md-7">
        <h4>Basic User Info</h4>
        <section class="candidate_info">
            <%= render 'shared/basic_candidate_info' %>
        </section>
    </aside>
    <div class="col-md-5 action-item">
        <ul class="action-list btn btn-lg btn-primary action-button">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    ACTIONS<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <% application = @application.id %>
                    <li><%= link_to "APPROVE" , application_approve_path(:id => application), method: :patch %></li>
                    <li><%= link_to "REJECT" , application_reject_path(:id => application), method: :patch %></li>
                    <li><%= link_to "EDIT" , edit_application_path %></li>
                    <li><%= link_to "DELETE", @application, method: :delete,
                                  data: { confirm: "You sure?" } %></li>
                </ul>
            </li>
        </ul>
        <%= link_to "SCHEDULE AN INTERVIEW", new_interview_path(:id => @application.id), class: "btn btn-lg btn-primary action-button" %>
    </div>
</div>
<% if @app_interviews.present? %>
    <div class="container timeline-container">
        <div class="row">
            <%= render 'shared/timeline' %>
        </div>
    </div>
<% end %>

hiring_manager_bc/app/views/feedbacks/index.html.erb
<h1>Welcome! <%= current_user.name %></h1>
  <% if @feedbacks.any? == true %>
  </div>
    <table class="table">
      <thead>
        <tr>
          <th>S.No</th>
          <th>ROUND</th>
          <th>FEEDBACK</th>
        </tr>
      </thead>
      <% @feedbacks.each do |feedback| %>
        <% interview = @interviews.find_by(id: feedback.interview_id) %>
        <tr>
          <td><%= feedback.id%></td>
          <td><%= interview.interview_type %></td>
          <td><%= feedback.message %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <h1>Sorry! but you don't have any feedbacks at the moment!</h1>
  <% end %>

hiring_manager_bc/app/views/interviews/new.html.erb
<%= render 'shared/interview_form' %>

hiring_manager_bc/app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="copyright-text">© BeautifulCode 2019</p>
</footer>

hiring_manager_bc/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
            <%= link_to "Hiring manager", root_path, id: "logo" %>
            <% if logged_in? %>
            
            <nav>
                <ul class="nav navbar-nav navbar-right nav-item">
                    <li><%= link_to "Application",   applications_path  %></li>
                    <li><%= link_to "Feedback",   feedbacks_path %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <%= current_user.name %><b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", applications_path %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Log out", logout_path, method: :delete %>
                        </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        <% end %>
    </div>
</header>

hiring_manager_bc/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

hiring_manager_bc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiring Manager | BeautifulCode</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container main-container">
      <%= yield %>
      <%= @user_id %>
    </div>
  </body>
</html>

hiring_manager_bc/app/views/shared/_basic_candidate_info.html.erb
<div class="info_container">
    <div class="row">
        <div class="col-md-6">
            <label>Name</label>
        </div>
        <div class="col-md-6">
            <p><%= @candidate.name %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <label>Email</label>
        </div>
        <div class="col-md-6">
            <p><%= @candidate.email %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <label>Phone</label>
        </div>
        <div class="col-md-6">
            <p><%= @application.contact_number %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <label>Status</label>
        </div>
        <div class="col-md-6">
            <p><%= @application.status %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <label>Resume</label>
        </div>
        <div class="col-md-6">
            <p><%= link_to @application.resume, '/uploads/application/resume/3/flower.jpeg' %></p>
        </div>
    </div>
</div>

hiring_manager_bc/app/views/shared/_error_messages.html.erb
<% if @application.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@application.errors.count, "error") %>.
    </div>
    <ul>
    <% @application.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

hiring_manager_bc/app/views/shared/_feedback_form.html.erb
<%= form_for(@feedback) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.label :feedback %>
      <%= f.text_field :message, class: 'form-control'%>

      <br>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>

hiring_manager_bc/app/views/shared/_interview_form.html.erb
<div>
  <%= form_for(@interview) do |f| %>
      <div class="field">
        <%= f.hidden_field :application_id, :value => params[:id] %>

        <%= f.label :interview_round %>
        <%= f.text_field :interview_type, class: 'form-control'%>

        <%= f.label :Interviewer %>
        <%= f.text_field :assignee, class: 'form-control'%>
        <br>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
</div>

hiring_manager_bc/app/views/shared/_timeline.html.erb
<% if @app_interviews.present? %>
    <div class="col-md-8">
        <section class="container">
        <header>
        <h1>Candidate Timeline</h1>
        </header>
        <section class="timeline">
            <figure class="timeline--inner">
                <% @app_interviews.each do |t| %>
                    <i class="timeline--inner-pin is-featured" data-title=<%= t.interview_type %>></i>
                <% end %>
            </figure>
        </section>
        </section>
    </div>
<% end %>